name: NobilityItems
version: 0.1.0
main: net.civex4.nobilityitems.NobilityItems
api-version: 1.14
commands:
  niget:
    description: Gets a NobilityItem and puts it in your hand
    usage: /niget <item_name>
  nilist:
    description: Lists out all loaded NobilityItems
    usage: /nilist
  nicreate:
    description: Creates a NobilityItem from the item in your hand
    usage: /nicreate <item_name>