name: NobilityItems
version: ${project.version}
main: net.civex4.nobilityitems.NobilityItems
api-version: 1.16
depend:
  - ProtocolLib
  - NobilityPatch
commands:
  nobilityitems:
    description: NobilityItems command
    usage: /nobilityitems (argument) ([other stuff...])
    aliases: [ni]
